apiVersion: fleet.cattle.io/v1alpha1
kind: ClusterGroup
metadata:
  name: test-group
  namespace: fleet-default
spec:
  selector:
    matchLabels:
      name: second
      # management.cattle.io/cluster-display-name: custom
